#! /bin/bash -e
mmcli -V | head -1 || echo "ModemManager not installed"
sudo apt update

# Install libqmi from source (removed libmbim-glib-dev)
apt-get install -y devscripts meson bash-completion gobject-introspection \
    libgirepository1.0-dev libglib2.0-dev libgudev-1.0-dev \
    libqrtr-glib-dev gtk-doc-tools help2man glib-2.0 libglib2.0 libglib2.0-doc
mkdir -p /home/gnome/mmup
cd /home/gnome/mmup
git clone https://gitlab.freedesktop.org/mobile-broadband/libqmi.git
cd libqmi
git checkout 1.36.0
meson setup build --prefix=/usr -Dmbim_qmux=false -Dqrtr=false -Dbash_completion=false --buildtype=release
ninja -C build install

# Install modemmanager
apt-get install -y meson cmake bash-completion gnome-common gobject-introspection intltool \
    libdbus-1-dev libgirepository1.0-dev libgudev-1.0-dev libpolkit-gobject-1-dev \
    libsystemd-dev python3-dbus python3-gi
cd /home/gnome/mmup
curl https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/archive/1.24.0/ModemManager-1.24.0.tar.gz | tar zxf -
cd ModemManager-1.24.0
meson setup build --prefix=/usr --buildtype=release --sysconfdir=/etc -Dmbim=false -Dqrtr=false -Dgtk_doc=false -Dbash_completion=false -Dsystemd_suspend_resume=false -Dat_command_via_dbus=true
ninja -C build install
